apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: awnvrbr1n-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-09998c0067.4lr8.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:e334814a26bad40f86ea3d2d57b84774d8c20809@sha256:29a5e10e0550a0423f6a5b6c9b483e25442a8affa10422da3be88995a6131c0b
          name: container-image
